/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\parallel\Downloads\room\record.glb -t -s -i -T -S 
Files: C:\Users\parallel\Downloads\room\record.glb [108.04KB] > C:\Users\parallel\record-transformed.glb [22.37KB] (79%)
*/

import { useGLTF, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useMemo, useRef } from "react";
import { Group, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

import { LP_GAP, LP_ROOT } from "@/constants/lp";
import { Album } from "@/types/Album";
import { LpManager } from "../managers/LpManager";

type GLTFResult = GLTF & {
    nodes: {
        ["Box001_Material_#25_0"]: THREE.Mesh;
        ["Box001_Material_#25_0_1"]: THREE.Mesh;
        ["Box001_Material_#25_0_2"]: THREE.Mesh;
        ["Box001_Material_#25_0_3"]: THREE.Mesh;
        vinyl158_Vinyl1_0: THREE.Mesh;
        vinyl158_Vinyl1_0_1: THREE.Mesh;
    };
    materials: {
        Material_25: THREE.MeshStandardMaterial;
        Material_37: THREE.MeshStandardMaterial;
        Material_49: THREE.MeshStandardMaterial;
        Material_73: THREE.MeshStandardMaterial;
        Vinyl1: THREE.MeshStandardMaterial;
        Vinyl2: THREE.MeshStandardMaterial;
    };
};

export function CustomLp({ album, order }: { album: Album; order: number }) {
    const { nodes, materials } = useGLTF(
        "/record-transformed.glb"
    ) as GLTFResult;
    const albumTexture = useTexture(album.cover);
    const coverMaterial = useMemo(() => {
        const material = new MeshStandardMaterial({ map: albumTexture });
        material.roughness = 1;
        material.metalness = 0.7;

        return material;
    }, [albumTexture]);

    const groupRef = useRef<Group>(null);
    const lpManager = new LpManager(album, order, groupRef);

    // 각 CustomLp가 자신의 애니메이션을 업데이트함
    useFrame(lpManager.onFrame);

    return (
        <group
            name={`lpOBJ-${album.id}`}
            ref={groupRef}
            position-x={order * LP_GAP}
            rotation-x={LP_ROOT.ROT.init[0]}
            onClick={lpManager.onClick}
            dispose={null}
        >
            <group name="cover">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes["Box001_Material_#25_0"].geometry}
                    material={coverMaterial}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes["Box001_Material_#25_0_1"].geometry}
                    material={materials.Material_37}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes["Box001_Material_#25_0_2"].geometry}
                    material={materials.Material_49}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes["Box001_Material_#25_0_3"].geometry}
                    material={materials.Material_73}
                />
            </group>
            <group
                name="record"
                rotation-z={-Math.PI / 2}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.vinyl158_Vinyl1_0.geometry}
                    material={materials.Vinyl1}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.vinyl158_Vinyl1_0_1.geometry}
                    material={materials.Vinyl2}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/record-transformed.glb");
