/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\parallel\Downloads\room\player.glb -t -s -i -T -S 
Files: C:\Users\parallel\Downloads\room\player.glb [2.33MB] > C:\Users\parallel\player-transformed.glb [212.47KB] (91%)
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Group } from "three";

type ActionName = "Start" | "[액션 제외]" | "Open";

interface GLTFAction extends THREE.AnimationClip {
    name: ActionName;
}

type GLTFResult = GLTF & {
    nodes: {
        Axis: THREE.Mesh;
        Object_5001: THREE.Mesh;
        Object_5001_1: THREE.Mesh;
        Object_5001_2: THREE.Mesh;
        Object_5001_3: THREE.Mesh;
        Object_5001_4: THREE.Mesh;
        Object_3001: THREE.Mesh;
        Object_3001_1: THREE.Mesh;
        Object_0006: THREE.Mesh;
        Object_0006_1: THREE.Mesh;
        Object_0006_2: THREE.Mesh;
        Object_0006_3: THREE.Mesh;
        Object_0006_4: THREE.Mesh;
    };
    materials: {
        steel: THREE.MeshStandardMaterial;
        plastic: THREE.MeshStandardMaterial;
        colored: THREE.MeshStandardMaterial;
        metal: THREE.MeshStandardMaterial;
        ["steel_2.0"]: THREE.MeshStandardMaterial;
        glass: THREE.MeshStandardMaterial;
        wood: THREE.MeshStandardMaterial;
    };
    animations: GLTFAction[];
};

export const Player = (props: JSX.IntrinsicElements["group"]) => {
    const group = useRef<Group>(null);

    const { nodes, materials, animations } = useGLTF(
        "/player-transformed.glb"
    ) as GLTFResult;
    const { actions } = useAnimations(animations, group);

    useEffect(() => {
        const init = async () => {
            await new Promise((res) => setTimeout(res, 300));
            const open = actions["Open"];

            if (!open) return;

            open.clampWhenFinished = true;
            open.setLoop(THREE.LoopRepeat, 1).play();
        };

        init();

        // TODO: Add subscribe playing and play anims
    }, []);

    return (
        <group
            ref={group}
            {...props}
            dispose={null}
        >
            <group
                name="Player002"
                position={[-0.012, 0.706, -1.243]}
                rotation={[Math.PI, 0, 0]}
                scale={0.7}
            >
                <pointLight
                    position={[-0.1, -0.5, 0.8]}
                    intensity={0.1}
                    color="#888"
                />
                <mesh
                    name="Axis"
                    castShadow
                    receiveShadow
                    geometry={nodes.Axis.geometry}
                    material={materials.steel}
                    position={[0.137, -0.117, 0.098]}
                    rotation={[Math.PI / 2, 0, 0.571]}
                >
                    <group
                        name="Needle"
                        position={[0.001, -0.001, 0.01]}
                        rotation={[1.54, -0.576, -0.017]}
                    >
                        <mesh
                            name="Object_5001"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_5001.geometry}
                            material={materials.steel}
                        />
                        <mesh
                            name="Object_5001_1"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_5001_1.geometry}
                            material={materials.plastic}
                        />
                        <mesh
                            name="Object_5001_2"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_5001_2.geometry}
                            material={materials.colored}
                        />
                        <mesh
                            name="Object_5001_3"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_5001_3.geometry}
                            material={materials.metal}
                        />
                        <mesh
                            name="Object_5001_4"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_5001_4.geometry}
                            material={materials["steel_2.0"]}
                        />
                    </group>
                </mesh>
                <group
                    name="Case"
                    position={[-0.002, -0.095, 0.179]}
                    rotation={[2.548, 0, 0]}
                >
                    <mesh
                        name="Object_3001"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_3001.geometry}
                        material={materials.metal}
                    />
                    <mesh
                        name="Object_3001_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_3001_1.geometry}
                        material={materials.glass}
                    />
                </group>
            </group>
            <group
                name="Body"
                position={[-0.012, 0.706, -1.243]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.7}
            >
                <mesh
                    name="Object_0006"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_0006.geometry}
                    material={materials.wood}
                />
                <mesh
                    name="Object_0006_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_0006_1.geometry}
                    material={materials.glass}
                />
                <mesh
                    name="Object_0006_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_0006_2.geometry}
                    material={materials.metal}
                />
                <mesh
                    name="Object_0006_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_0006_3.geometry}
                    material={materials.plastic}
                />
                <mesh
                    name="Object_0006_4"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_0006_4.geometry}
                    material={materials.steel}
                />
            </group>
        </group>
    );
};

useGLTF.preload("/player-transformed.glb");
