/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\parallel\Downloads\room\room.glb -t -i -T -S -s 
Files: C:\Users\parallel\Downloads\room\room.glb [94.83MB] > C:\Users\parallel\room-transformed.glb [538.2KB] (99%)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Tablet_Baked: THREE.Mesh;
        Table_Baked: THREE.Mesh;
        Shelf_Baked: THREE.Mesh;
        BgRecords_Baked: THREE.Mesh;
        Room_Baked: THREE.Mesh;
        Room001_Baked: THREE.Mesh;
    };
    materials: {
        Tablet_Baked: THREE.MeshStandardMaterial;
        Table_Baked: THREE.MeshStandardMaterial;
        Shelf_Baked: THREE.MeshStandardMaterial;
        ["BgRecords_Baked.001"]: THREE.MeshStandardMaterial;
        Room_Baked: THREE.MeshStandardMaterial;
        ["Room.001_Baked"]: THREE.MeshStandardMaterial;
    };
};

export const RoomBaked = (props: JSX.IntrinsicElements["group"]) => {
    const { nodes, materials } = useGLTF("/room-transformed.glb") as GLTFResult;

    materials.Table_Baked.emissiveIntensity = 0.05;
    materials.Table_Baked.emissive = new THREE.Color(0.1, 0.1, 0.1);
    materials["Room.001_Baked"].emissiveIntensity = 0.1;
    materials["Room.001_Baked"].emissive = new THREE.Color(0.5, 0.5, 0.5);

    return (
        <group
            {...props}
            dispose={null}
        >
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Tablet_Baked.geometry}
                material={materials.Tablet_Baked}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Table_Baked.geometry}
                material={materials.Table_Baked}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Shelf_Baked.geometry}
                material={materials.Shelf_Baked}
                position={[0, 2, -1.404]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.BgRecords_Baked.geometry}
                material={materials["BgRecords_Baked.001"]}
            />
            <mesh
                receiveShadow
                geometry={nodes.Room_Baked.geometry}
                material={materials.Room_Baked}
                position={[0, -0.131, -0.208]}
            />
            <mesh
                receiveShadow
                geometry={nodes.Room001_Baked.geometry}
                material={materials["Room.001_Baked"]}
                position={[0, -0.131, -0.208]}
            />
        </group>
    );
};

useGLTF.preload("/room-transformed.glb");
