/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\parallel\Downloads\room\room.glb -t -s -i -T - S 
Files: C:\Users\parallel\Downloads\room\room.glb [26.77MB] > C:\Users\parallel\room-transformed.glb [819.66KB] (97%)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Mesh018: THREE.Mesh;
        Mesh018_1: THREE.Mesh;
        Mesh018_2: THREE.Mesh;
        Mesh018_3: THREE.Mesh;
        Mesh018_4: THREE.Mesh;
        Mesh018_5: THREE.Mesh;
        Mesh018_6: THREE.Mesh;
        Mesh018_7: THREE.Mesh;
        Cube005: THREE.Mesh;
        Cube005_1: THREE.Mesh;
        Table_1: THREE.Mesh;
        Table_2: THREE.Mesh;
        Mesh043: THREE.Mesh;
        Mesh043_1: THREE.Mesh;
        Mesh043_2: THREE.Mesh;
        Room: THREE.Mesh;
        Shelf: THREE.Mesh;
    };
    materials: {
        ["Dark.Wood.004"]: THREE.MeshStandardMaterial;
        PaletteMaterial005: THREE.MeshStandardMaterial;
        PaletteMaterial006: THREE.MeshStandardMaterial;
        PaletteMaterial007: THREE.MeshStandardMaterial;
        PaletteMaterial001: THREE.MeshStandardMaterial;
        PaletteMaterial002: THREE.MeshStandardMaterial;
        PaletteMaterial003: THREE.MeshStandardMaterial;
        PaletteMaterial004: THREE.MeshStandardMaterial;
        ["Audio.Body.003"]: THREE.MeshStandardMaterial;
        ["Material.002"]: THREE.MeshStandardMaterial;
        PaletteMaterial009: THREE.MeshPhysicalMaterial;
        PaletteMaterial008: THREE.MeshPhysicalMaterial;
        ["20.-.Default.001"]: THREE.MeshStandardMaterial;
        PaletteMaterial010: THREE.MeshStandardMaterial;
        ["14.-.Default.001"]: THREE.MeshStandardMaterial;
        PaletteMaterial011: THREE.MeshStandardMaterial;
        ["Dark.Wood.004"]: THREE.MeshStandardMaterial;
    };
};

export const SceneModel = ({
    children,
    ...props
}: JSX.IntrinsicElements["group"] & { children?: React.ReactNode }) => {
    const { nodes, materials } = useGLTF("/room-transformed.glb") as GLTFResult;
    return (
        <group
            {...props}
            dispose={null}
        >
            {children}
            <group
                name="player"
                position={[0, 0.66, -1.115]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh018.geometry}
                    material={materials["Dark.Wood.004"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh018_1.geometry}
                    material={materials.PaletteMaterial005}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh018_2.geometry}
                    material={materials.PaletteMaterial006}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh018_3.geometry}
                    material={materials.PaletteMaterial007}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh018_4.geometry}
                    material={materials.PaletteMaterial001}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh018_5.geometry}
                    material={materials.PaletteMaterial002}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh018_6.geometry}
                    material={materials.PaletteMaterial003}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh018_7.geometry}
                    material={materials.PaletteMaterial004}
                />
            </group>
            <group
                name="audio"
                position={[0.5, 0, -1.206]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube005.geometry}
                    material={materials["Audio.Body.003"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube005_1.geometry}
                    material={materials["Material.002"]}
                />
            </group>
            <group
                name="table"
                position={[0, 0, -1.115]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Table_1.geometry}
                    material={materials.PaletteMaterial009}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Table_2.geometry}
                    material={materials.PaletteMaterial008}
                />
            </group>
            <group
                name="tablet"
                position={[0, 0, -1.2]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh043.geometry}
                    material={materials["20.-.Default.001"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh043_1.geometry}
                    material={materials.PaletteMaterial010}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh043_2.geometry}
                    material={materials["14.-.Default.001"]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Room.geometry}
                material={materials.PaletteMaterial011}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Shelf.geometry}
                material={materials["Dark.Wood.004"]}
            />
        </group>
    );
};

useGLTF.preload("/room-transformed.glb");
