/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\parallel\Downloads\room\speakers.glb -t -i -T -S -s 
Files: C:\Users\parallel\Downloads\room\speakers.glb [20.17MB] > C:\Users\parallel\speakers-transformed.glb [1.4MB] (93%)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Object_25001: THREE.Mesh;
        Object_25001_1: THREE.Mesh;
        Object_25001_2: THREE.Mesh;
        Object_25001_3: THREE.Mesh;
        Object_25001_4: THREE.Mesh;
        Object_25001_5: THREE.Mesh;
        Object_25001_6: THREE.Mesh;
        Object_25001_7: THREE.Mesh;
        Object_25001_8: THREE.Mesh;
        Object_25001_9: THREE.Mesh;
        Object_25001_10: THREE.Mesh;
        Object_25002: THREE.Mesh;
        Object_25002_1: THREE.Mesh;
    };
    materials: {
        pierscien: THREE.MeshStandardMaterial;
        lightgray: THREE.MeshStandardMaterial;
        black: THREE.MeshStandardMaterial;
        darkgraymetal: THREE.MeshStandardMaterial;
        material: THREE.MeshStandardMaterial;
        pierscienczarn: THREE.MeshStandardMaterial;
        membrane_cooper: THREE.MeshStandardMaterial;
        membrane: THREE.MeshStandardMaterial;
        guma: THREE.MeshStandardMaterial;
        darkwood: THREE.MeshStandardMaterial;
        brownwood: THREE.MeshStandardMaterial;
        ["pierscien.001"]: THREE.MeshStandardMaterial;
        ["lightgray.001"]: THREE.MeshStandardMaterial;
    };
};

export const Speakers = (props: JSX.IntrinsicElements["group"]) => {
    const { nodes, materials } = useGLTF(
        "/speakers-transformed.glb"
    ) as GLTFResult;

    return (
        <group
            {...props}
            dispose={null}
        >
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_25001.geometry}
                material={materials.pierscien}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_25001_1.geometry}
                material={materials.lightgray}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_25001_2.geometry}
                material={materials.black}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_25001_3.geometry}
                material={materials.darkgraymetal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_25001_4.geometry}
                material={materials.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_25001_5.geometry}
                material={materials.pierscienczarn}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_25001_6.geometry}
                material={materials.membrane_cooper}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_25001_7.geometry}
                material={materials.membrane}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_25001_8.geometry}
                material={materials.guma}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_25001_9.geometry}
                material={materials.darkwood}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_25001_10.geometry}
                material={materials.brownwood}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_25002.geometry}
                material={materials["pierscien.001"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_25002_1.geometry}
                material={materials["lightgray.001"]}
            />
        </group>
    );
};

useGLTF.preload("/speakers-transformed.glb");
